version: "3.8"

services:
  postgres:
    container_name: query_builder_js_container
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=queryBuilderJs
    volumes:
      - query_builder_js_pg_data:/bitnami/postgresql

volumes:
  query_builder_js_pg_data: